import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Event: Chrisdun</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://cdn.splitbee.io/sb.js"></script>
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <div className="prose">
          <h1 className="py-2">Christian og Reiduns bryllup!</h1>
        </div>

        <div className="info flex flex-col gap-2">
          <span>Time: August 4th at 3pm - August 7th at 1pm</span>
          <span>Place: Nøsen Fjellhotell</span>
        </div>

        <div className="py-2" />

        <div className="description prose">
          <p>Hei alle sammen!</p>
          <p>Her kommer mer informasjon om bryllupet vårt i august! 💍</p>
          <h3>Program 📜</h3>
          <p>
            Vi har booket hotellet torsdag 4. til søndag 7. august. Dere kommer
            så tidlig dere har lyst og mulighet til. For de som har mulighet til
            å være med helt fra torsdag blir det frilek, middag og sosialisering
            på Nøsen. På fredag er det mulighet for tur, bading, yoga og å være
            med på eventuelle bryllupsforberedelser. Det viktigste å få med seg
            er lørdagen. Da blir det seremoni i 13/14-tiden etterfulgt av
            bobler, lett servering, bilder, mingling og etter hvert middag og
            fest. Søndag er avreisedag.
          </p>
          <p></p>
          <h3>Praktisk info 🏤</h3>
          <p>
            Vi har booket hele hotellet, dvs. at det ikke kommer til å være
            andre gjester der samtidig med oss. Dere trenger altså ikke å
            kontakte hotellet for å booke rom. Hver gjest betaler 700 kr per
            natt for overnatting og frokost. Hva den enkelte betaler kommer
            altså an på hvor mange netter man er på hotellet. Resten av
            måltidene (lunsj+middag) spanderer vi. Det er en liten kiosk på
            Nøsen der man kan kjøpe snacks hvis man vil, og en matbutikk 15 min
            unna med bil.
          </p>
          <p>
            Gi oss beskjed om hvilken dag dere kommer så snart dere finner ut av
            planene deres, så får vi bestilt riktig mengde mat. Vi gir beskjed
            om hvordan vi gjør det med betaling for hotellet når bryllupet
            nærmer seg.
          </p>
          <h3>Taler/underholdning 🎤</h3>
          <p>
            Taler og andre små underholdningsinnslag er hyggelig! Vår
            toastmaster Karethe styrer showet. Hvis du har lyst til å
            tale/lese/synge/spille/hvasomhelst under middagen, send mail i god
            tid til karetheht@gmail.com. Vi har noen engelsktalende gjester, men
            seremonien blir på norsk, og man holder taler på det språket man er
            mest komfortabel med. Hvis man har skrevet ned en norsk tale på
            forhånd kan Karethe skrive en oversettelse som de engelsktalende kan
            følge med på mens man holder talen. Det samme gjelder
            dikt/sanger/hvasomhelst, Karethe er en dyktig dame.
          </p>
          <p>Vi gleder oss masse til å feire med dere! 👩🏼‍🦱👨🏻‍🦰</p>
        </div>
        <div className="attendees"></div>
      </div>
    </>
  );
};

export default Home;
